{% set name = "certipy" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fef1f3d8819ee29c4c67719171c988302823dfe0b6cfbb47d249f374809ba05e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{version}}
  entry_points:
    - certipy = certipy.command_line:main

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=64
    - setuptools-scm >=7
  run:
    - python
    - cryptography

test:
  requires:
    - pip
  imports:
    - certipy
  commands:
    - pip check
    - certipy test

about:
  home: https://github.com/LLNL/certipy
  license: BSD-3-Clause
  license_family: BSD
  # LICENSE file is missing from sdist, but present in repo
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'
  description: |
    A simple python tool for creating certificate authorities
    and certificates on the fly.
  dev_url: https://github.com/LLNL/certipy
  doc_url: https://github.com/LLNL/certipy

extra:
  recipe-maintainers:
    - minrk
